image: node:10

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build

deploy:
  stage: deploy
  environment: Firebase
  only:
    - master
  before_script:
    - yarn global add firebase-tools
  script:
    - firebase use --token $FIREBASE_DEPLOY_KEY ng-material-crank
    - firebase deploy --token $FIREBASE_DEPLOY_KEY --non-interactive -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
