image: node:10

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn clean
    - yarn build

deploy:
  stage: deploy
  environment: Firebase
  only:
    - master
  before_script:
    - yarn global add firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN --non-interactive -m "Pipeline $CI_PIPELINE_ID, Build $CI_BUILD_ID"
