cache:
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts-alpine
  before_script:
    - yarn
  script:
    - yarn clean
    - yarn build

deploy:
  stage: deploy
  image: andreysenov/firebase-tools:latest
  environment: Firebase
  only:
    - master
  script:
    - firebase deploy --token $FIREBASE_TOKEN --non-interactive -m "Pipeline $CI_PIPELINE_ID, Build $CI_BUILD_ID"
