version: '3'
services:
  dev:
    build: .
    image: ng-material-crank:dev
    container_name: ng-material-crank
    ports:
      - 8080:8080
    volumes:
      - .:/home/app/ng-material-crank
    tty: true
