version: '3'
volumes:
  node_modules:
services:
  dev:
    container_name: ng-material-crank
    image: node:lts-alpine
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    tty: true
