yarn upgrade ^
@types/node ^
angular2-template-loader ^
awesome-typescript-loader ^
clean-webpack-plugin ^
css-loader ^
extract-text-webpack-plugin ^
file-loader ^
html-loader ^
html-webpack-plugin ^
node-sass ^
reset-css ^
sass-loader ^
style-loader ^
typescript ^
url-loader ^
webpack ^
webpack-dev-server ^
@angular/animations ^
@angular/common ^
@angular/compiler ^
@angular/core ^
@angular/forms ^
@angular/http ^
@angular/material ^
@angular/platform-browser ^
@angular/platform-browser-dynamic ^
@angular/router ^
es6-shim ^
hammerjs ^
reflect-metadata ^
rxjs ^
zone.js
